### ISSUE TITLE
Spec fix

### ISSUE THREAD

**Issue by Madeline-Stark** [learn-co-students/rails-edit-update-action-readme-v-000#974]
Using form_for changes edit form params from title and description to post[title] and post[description]. Changing lines 41 and 42 in spec/features/post_spec.rb to this fixed it:

fill_in 'post[title]', with: "My edit"
fill_in 'post[description]', with: "My post description"

**Comment by tmetz** [comment]
In this case it actually changes them to article[title] and article[description].  Without changing the tests, changing the update action to:

def update
    @article = Article.find(params[:id])
    @article.update(title: params[:article][:title], description: params[:article][:description])
    redirect_to article_path(@article)
  end

fixed it.  I believe this is basically the same suggestion Eric Fiorani suggests.
